### ISSUE TITLE
Draw font performance issues

### ISSUE THREAD

**Issue by ColleagueRiley** [logos-maker/ikiGUI#2]
Your draw font code has many peonage issues.

1) you call the bitmap function every loop, this is really bad. 

2)  you use strlen() during to get the text size when you loop it

Strlen loops through the string until it finds '\0', this means you're looping through the string twice rather than checking yourself. 

These were two things I noticed at a first glance, there could be more.

**Comment by logos-maker** [comment]
1. Each iteration of the loop generates one letter, so it has to be called.
2. strlen will not be called more that once, as it will optimizer will generate one call and get the number and iterate that amount.
 
And this function is used to composite images that you do one time when you start your program,  and is not to print text in realtime. I will make other code later that uses stbtt_BakeFontBitmap that renders all characters one time to be able to reuse them to draw text during runtime.

**Comment by ColleagueRiley** [comment]
1) It should not be called each loop, this is awful for performance. You have to create some sort of loading before it.

2) You do not need to call it at all since you're looping the string.

```c
for (int i = 0; i < strlen(word); ++i)
```

should be 

```c
for (int i = 0; word[i]; ++i);
```

The source code of strlen looks something like this

```c
size_t strlen(const char* _str) {
    char* str = (char*)_str;
    for (str; *str; str++);
    
    return (size_t)(str - _str);
}
```

**Comment by ColleagueRiley** [comment]
> not to print text in realtime. I will make other code later that uses stbtt_BakeFontBitmap that renders all characters one time to be able to reuse them to draw text during runtime.

The function was called draw_text, so I assumed it was called in runtime. 

The code seems like test code so I already assumed you'd change it in the future. I'm mostly writing this issue so that way the new version doesn't have the same mistake. Sorry if this comes off as overly judgmental or rude.

**Comment by logos-maker** [comment]
> 1. It should not be called each loop, this is awful for performance. You have to create some sort of loading before it.
> 
>     2. You do not need to call it at all since you're looping the string.
> 
> 
> ```c
> for (int i = 0; i < strlen(word); ++i)
> ```
> 
> should be
> 
> ```c
> for (int i = 0; word[i]; ++i);
> ```
> 
> The source code of strlen looks something like this
> 
> ```c
> size_t strlen(const char* _str) {
>     char* str = (char*)_str;
>     for (str; *str; str++);
>     
>     return (size_t)(str - _str);
> }
> ```
1. stbtt_MakeCodepointBitmap() can only create one letter, so it has to be done every iteration.
2. It's not a server application that parses billions of characters per second. But then it 
would be faster with something like...
```
for(int letter, i = 0 ; letter = word[i] ; i++ )
```
 I will make other code later that uses stbtt_BakeFontBitmap that renders all characters one time to be able to reuse them.

If you find something in a inner loop that will be done millions of times per second then it matters. Not something that takes a couple of cycles one time, we don't live in the 1960's then it maybe would  had mattered.

**Comment by ColleagueRiley** [comment]
You have no idea how much data will be passed unless you're the user creating the function.

Sure, it probably doesn't create any significant performance issues. But it doesn't make sense to waste the cycle when it requires little to no extra work to fix.

The cycle waste can also add up if you expect this function to be ran more than once. Which again, a function called "draw_text" seems like it will be ran more than once.
